services:
  postgres: # 数据库
    image: 'postgres:latest'
    container_name: oj_db
    restart: always
    environment:
      - 'POSTGRES_DB=oj'  # 默认数据库
      - 'POSTGRES_PASSWORD=Lird2002'  # 使用文件中的密码保证安全性
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data  # 数据持久化到本地目录
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql # 初始化数据库的sql脚本
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
  adminer:  # 数据库管理
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq: # 消息队列中间件
    container_name: oj_mq
    restart: always
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=oj'
    ports:
      - '5672'
  redis:  # redis缓存
    image: 'redis:latest'
    restart: always
    container_name: oj_redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/etc/redis/redis.conf
secrets:  # 密码文件配置
  mq_pwd:
    file: ./config/pwd/mq_pwd.txt