spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/oj
    password: Lird2002
    username: oj
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 8
          max-wait: -1
          min-idle: 0
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: oj
    password: secret
server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0